//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthConditionGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthConditionGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82661006
        ///289080009
        ///289086003
        ///26741000
        ///42170009
        ///24414006
        ///130962007
        ///109562007
        ///274688009
        ///274127000
        ///418286009
        ///274855004
        ///67809006
        ///28154007
        ///72014004
        ///288210004
        ///199733009
        ///274833007
        ///274862008
        ///302644007
        ///302078000
        ///274845003
        ///123667006
        ///42131003
        ///274681003
        ///700153004
        ///301783004
        ///56313000
        ///102882004
        ///11082009
        ///39804004
        ///90009001
        ///44991000119100
        ///312984006
        ///301822002
        ///62917007
        ///237288003
        ///17588005
        ///35882009
        ///1639007
        ///3885002
        ///428508008
        ///16038004
        ///69302000
        ///45581006
        ///19707006
        ///52895001
        ///51623004
        ///4469 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleExclusiveConcepts {
            get {
                return ResourceManager.GetString("FemaleExclusiveConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82661006
        ///289080009
        ///289086003
        ///26741000
        ///42170009
        ///109562007
        ///274127000
        ///67809006
        ///72014004
        ///288210004
        ///199733009
        ///302644007
        ///302078000
        ///123667006
        ///42131003
        ///301783004
        ///56313000
        ///102882004
        ///11082009
        ///39804004
        ///71067002
        ///4529005
        ///90009001
        ///237288003
        ///17588005
        ///35882009
        ///1639007
        ///3885002
        ///428508008
        ///16038004
        ///69302000
        ///102885002
        ///302945005
        ///735635007
        ///735631003
        ///236812009
        ///236809006
        ///236810001
        ///198014000
        ///735636008
        ///735632005
        ///43651009
        ///236811002
        ///28911003
        ///416413003
        ///237337003
        ///74437002
        ///10754331000119108
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FertilityConditions {
            get {
                return ResourceManager.GetString("FertilityConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14	24	34	44	54	65	74	84	150
        ///0.001449275	0.00611477	0.002961083	0.002460457	0.001243163	0.001603849	0.001360313	0.000323939	0
        ///0.001449275	0.00611477	0.002961083	0.002460457	0.002734958	0.003007217	0.003230743	0.002591513	0.002747672
        ///0.001449275	0.007055503	0.003384095	0.005623902	0.005221283	0.008019246	0.009692229	0.008584386	0.007632423
        ///0.001449275	0.007055503	0.003807107	0.005623902	0.006215813	0.008420209	0.010032307	0.009880143	0.007632423
        ///0.004347826	0.024929445	0.019881557	0.025659051	0.015663849 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HealthConditions_Female {
            get {
                return ResourceManager.GetString("HealthConditions_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14	24	34	44	54	65	74	84	150
        ///0.001048218	0	0.001085776	0.002678571	0.002801993	0.000900495	0.001496166	0.001212751	0
        ///0.001048218	0	0.001085776	0.004017857	0.005915318	0.003601981	0.00486254	0.005890506	0.009693878
        ///0.003144654	0	0.002171553	0.005357143	0.006849315	0.011931562	0.012904432	0.01992377	0.022789116
        ///0.003144654	0	0.004885993	0.005357143	0.006849315	0.011931562	0.012904432	0.01992377	0.022789116
        ///0.00524109	0	0.004885993	0.005357143	0.009339975	0.014407924	0.015148682	0.021309771	0.025510204
        ///0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HealthConditions_Male {
            get {
                return ResourceManager.GetString("HealthConditions_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57514000
        ///300525002
        ///446551005
        ///5049001
        ///274685007
        ///386674000
        ///274852001
        ///274835000
        ///274860000
        ///274846002
        ///5413009
        ///274682005
        ///4529005
        ///50293005
        ///18823009
        ///84204007
        ///57971009
        ///9090007
        ///211064009
        ///211048001
        ///57593007
        ///20025003
        ///39729001
        ///36029005
        ///8725005
        ///27717006
        ///42855005
        ///18957000
        ///95593001
        ///33724004
        ///39235000
        ///42288005
        ///249239007
        ///249233008
        ///237804005
        ///721554002
        ///311497003
        ///236756001
        ///735635007
        ///735631003
        ///236775006
        ///236812009
        ///236809006
        ///236810001
        ///198014000
        ///1051000119103
        ///266571009
        ///735636008
        ///735632 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleExclusiveConcepts {
            get {
                return ResourceManager.GetString("MaleExclusiveConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;40733004
        ///&lt;372130007
        ///&lt;363346000 minus &lt;372130007
        ///&lt;399981008 minus &lt;363346000
        ///&lt;165423001 OR &lt;165397008
        ///&lt;414022008 minus (&lt;165423001 OR &lt;165397008)
        ///&lt;14304000
        ///&lt;46635009
        ///&lt;44054006
        ///&lt;68256003
        ///&lt;124042003
        ///&lt;362969004 OR &lt;297269007 OR &lt;75934005 OR &lt;2492009
        ///&lt;442351006
        ///&lt;35489007
        ///&lt;46206005 minus &lt;35489007
        ///&lt;79823003
        ///&lt;386808001
        ///&lt;191736004
        ///&lt;47505003
        ///&lt;48694002
        ///&lt;192562009
        ///&lt;384821006
        ///&lt;74732009 OR &lt;844005
        ///&lt;84757009
        ///&lt;37796009
        ///&lt;118940003
        ///&lt;247052002
        ///&lt;23986001
        ///&lt;82649003
        ///&lt;422338006
        ///&lt;41256004
        ///&lt;57190000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderedHealthConditions {
            get {
                return ResourceManager.GetString("OrderedHealthConditions", resourceCulture);
            }
        }
    }
}
