//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthConditionGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthConditionGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14	24	34	44	54	65	74	84	150
        ///0.001449275	0.00611477	0.002961083	0.002460457	0.001243163	0.001603849	0.001360313	0.000323939	0
        ///0.001449275	0.00611477	0.002961083	0.002460457	0.002734958	0.003007217	0.003230743	0.002591513	0.002747672
        ///0.001449275	0.007055503	0.003384095	0.005623902	0.005221283	0.008019246	0.009692229	0.008584386	0.007632423
        ///0.001449275	0.007055503	0.003807107	0.005623902	0.006215813	0.008420209	0.010032307	0.009880143	0.007632423
        ///0.004347826	0.024929445	0.019881557	0.025659051	0.015663849 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HealthConditions_Female {
            get {
                return ResourceManager.GetString("HealthConditions_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14	24	34	44	54	65	74	84	150
        ///0.001048218	0	0.001085776	0.002678571	0.002801993	0.000900495	0.001496166	0.001212751	0
        ///0.001048218	0	0.001085776	0.004017857	0.005915318	0.003601981	0.00486254	0.005890506	0.009693878
        ///0.003144654	0	0.002171553	0.005357143	0.006849315	0.011931562	0.012904432	0.01992377	0.022789116
        ///0.003144654	0	0.004885993	0.005357143	0.006849315	0.011931562	0.012904432	0.01992377	0.022789116
        ///0.00524109	0	0.004885993	0.005357143	0.009339975	0.014407924	0.015148682	0.021309771	0.025510204
        ///0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HealthConditions_Male {
            get {
                return ResourceManager.GetString("HealthConditions_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;40733004
        ///&lt;372130007
        ///&lt;363346000 minus &lt;372130007
        ///&lt;399981008 minus &lt;363346000
        ///&lt;165423001 OR &lt;165397008
        ///&lt;414022008 minus (&lt;165423001 OR &lt;165397008)
        ///&lt;14304000
        ///&lt;46635009
        ///&lt;44054006
        ///&lt;68256003
        ///&lt;124042003
        ///&lt;362969004 OR &lt;297269007 OR &lt;75934005 OR &lt;2492009
        ///&lt;442351006
        ///&lt;35489007
        ///&lt;46206005 minus &lt;35489007
        ///&lt;79823003
        ///&lt;386808001
        ///&lt;191736004
        ///&lt;47505003
        ///&lt;48694002
        ///&lt;192562009
        ///&lt;384821006
        ///&lt;74732009 OR &lt;844005
        ///&lt;84757009
        ///&lt;37796009
        ///&lt;118940003
        ///&lt;247052002
        ///&lt;23986001
        ///&lt;82649003
        ///&lt;422338006
        ///&lt;41256004
        ///&lt;57190000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderedHealthConditions {
            get {
                return ResourceManager.GetString("OrderedHealthConditions", resourceCulture);
            }
        }
    }
}
