//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.012097641
        ///0.023986563
        ///0.036473139
        ///0.048774576
        ///0.061081729
        ///0.073592996
        ///0.086002324
        ///0.098385296
        ///0.110840512
        ///0.123097649
        ///0.135390273
        ///0.147522449
        ///0.159242746
        ///0.170491461
        ///0.181576791
        ///0.19263084
        ///0.203717519
        ///0.215102946
        ///0.226955745
        ///0.239192796
        ///0.251762336
        ///0.264703344
        ///0.278070364
        ///0.292253917
        ///0.306646426
        ///0.321073868
        ///0.33569923
        ///0.350677326
        ///0.365936386
        ///0.381007527
        ///0.396069221
        ///0.411013655
        ///0.426060345
        ///0.440959923
        ///0.455742638
        ///0.470367366
        ///0.484506777
        ///0.498279722
        ///0.51153345
        ///0.524411 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleAgeSpread {
            get {
                return ResourceManager.GetString("FemaleAgeSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olivia
        ///Charlotte
        ///Mia
        ///Ava
        ///Amelia
        ///Emily
        ///Sofia
        ///Sophie
        ///Chloe
        ///Ruby
        ///Emma
        ///Elizabeth
        ///Harper
        ///Madison
        ///Caroline
        ///Isabella
        ///Ella
        ///Sophia
        ///Abigail
        ///Aurora
        ///Evelyn
        ///Lillian
        ///Addison
        ///Aria
        ///Scarlett
        ///Paisley
        ///Avery
        ///Brooklyn
        ///Camila
        ///Victoria
        ///Riley
        ///Aubrey
        ///Zoe
        ///Grace
        ///Mila
        ///Nora
        ///Natalie
        ///Skylar
        ///Lily
        ///Zoey
        ///Layla
        ///Ximena
        ///Hazel
        ///Lucy
        ///Claire
        ///Piper
        ///Hailey
        ///Angela  
        ///Tequila  
        ///Jacklyn  
        ///Ayana  
        ///Renay  
        ///Margot  
        ///Teresa  
        ///Eusebia  
        ///Treena  
        ///Tona  
        ///Tressa  
        ///Alyce  
        ///Ingrid  
        ///Kindra  
        ///Sherri  
        ///Ja [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstFemaleNames {
            get {
                return ResourceManager.GetString("FirstFemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oliver
        ///Jack
        ///William
        ///Mason
        ///James
        ///Hunter
        ///Noah
        ///Lucas
        ///Leo
        ///Max
        ///John
        ///Elijah
        ///Jackson
        ///Michael
        ///Liam
        ///Carter
        ///Joseph
        ///Owen
        ///Logan
        ///David
        ///Jacob
        ///Wyatt
        ///Benjamin
        ///Gabriel
        ///Henry
        ///Sebastian
        ///Daniel
        ///Alexander
        ///Julian
        ///Grayson
        ///Matthew
        ///Ethan
        ///Samuel
        ///Dylan
        ///Jayden
        ///Aiden
        ///Luke
        ///Ezekiel
        ///Lincoln
        ///Jaxon
        ///Theodore
        ///Kingston
        ///Ryker
        ///Anthony
        ///Josiah
        ///Isaiah
        ///Easton
        ///Hudson
        ///Jose
        ///Levi
        ///Sawyer
        ///Braxton
        ///Isaac
        ///Bridger
        ///Cooper
        ///Gordon  
        ///Dalton  
        ///Alphonse  
        ///Hosea  
        ///Jeramy  
        ///Johnie  
        ///Willis  
        ///Pete  
        ///Toby   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstMaleNames {
            get {
                return ResourceManager.GetString("FirstMaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.012292728
        ///0.025288495
        ///0.038054374
        ///0.050847083
        ///0.063902121
        ///0.076901669
        ///0.089831783
        ///0.102821899
        ///0.115636764
        ///0.128463702
        ///0.141165432
        ///0.153412305
        ///0.165189767
        ///0.176816288
        ///0.188302152
        ///0.199848628
        ///0.21167845
        ///0.223681003
        ///0.23591507
        ///0.248634443
        ///0.261711311
        ///0.275223442
        ///0.289345762
        ///0.303826471
        ///0.318522393
        ///0.333254699
        ///0.348295026
        ///0.363539793
        ///0.378549916
        ///0.393565567
        ///0.408465522
        ///0.423571584
        ///0.438495768
        ///0.453353933
        ///0.468110101
        ///0.482381777
        ///0.496314048
        ///0.509708247
        ///0.522724299
        ///0.53552 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialAgeDistribution {
            get {
                return ResourceManager.GetString("InitialAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Jones
        ///Williams
        ///Brown
        ///Wilson
        ///Taylor
        ///Johnson
        ///White
        ///Martin
        ///Anderson
        ///Thompson
        ///Nguyen
        ///Turner
        ///Walker
        ///Harris
        ///Lee
        ///Ryan
        ///Robinson
        ///Kelly
        ///King
        ///Smith
        ///Wilson
        ///Williams
        ///Brown
        ///Taylor
        ///Jones
        ///Singh
        ///Wang
        ///Anderson
        ///Li
        ///Thompson
        ///Walker
        ///Lee
        ///Chen
        ///Patel
        ///Zhang
        ///Martin
        ///King
        ///Harris
        ///Kumar.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.013000915
        ///0.02579355
        ///0.039227802
        ///0.052405536
        ///0.065574478
        ///0.078995339
        ///0.0922902
        ///0.105542712
        ///0.118843945
        ///0.131997319
        ///0.145136979
        ///0.158170805
        ///0.170744998
        ///0.182872543
        ///0.194855294
        ///0.206653319
        ///0.2185041
        ///0.230703358
        ///0.243342809
        ///0.256559585
        ///0.270015214
        ///0.283707273
        ///0.297970689
        ///0.313135223
        ///0.328397686
        ///0.34353318
        ///0.358626406
        ///0.37385636
        ///0.389224817
        ///0.404247864
        ///0.419237595
        ///0.434083096
        ///0.4490308
        ///0.463797329
        ///0.478548128
        ///0.493216567
        ///0.507494099
        ///0.521410087
        ///0.534770691
        ///0.547724981
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleAgeSpread {
            get {
                return ResourceManager.GetString("MaleAgeSpread", resourceCulture);
            }
        }
    }
}
