//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olivia
        ///Charlotte
        ///Mia
        ///Ava
        ///Amelia
        ///Emily
        ///Sofia
        ///Sophie
        ///Chloe
        ///Ruby
        ///Emma
        ///Elizabeth
        ///Harper
        ///Madison
        ///Caroline
        ///Isabella
        ///Ella
        ///Sophia
        ///Abigail
        ///Aurora
        ///Evelyn
        ///Lillian
        ///Addison
        ///Aria
        ///Scarlett
        ///Paisley
        ///Avery
        ///Brooklyn
        ///Camila
        ///Victoria
        ///Riley
        ///Aubrey
        ///Zoe
        ///Grace
        ///Mila
        ///Nora
        ///Natalie
        ///Skylar
        ///Lily
        ///Zoey
        ///Layla
        ///Ximena
        ///Hazel
        ///Lucy
        ///Claire
        ///Piper
        ///Hailey
        ///Angela  
        ///Tequila  
        ///Jacklyn  
        ///Ayana  
        ///Renay  
        ///Margot  
        ///Teresa  
        ///Eusebia  
        ///Treena  
        ///Tona  
        ///Tressa  
        ///Alyce  
        ///Ingrid  
        ///Kindra  
        ///Sherri  
        ///Ja [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstFemaleNames {
            get {
                return ResourceManager.GetString("FirstFemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oliver
        ///Jack
        ///William
        ///Mason
        ///James
        ///Hunter
        ///Noah
        ///Lucas
        ///Leo
        ///Max
        ///John
        ///Elijah
        ///Jackson
        ///Michael
        ///Liam
        ///Carter
        ///Joseph
        ///Owen
        ///Logan
        ///David
        ///Jacob
        ///Wyatt
        ///Benjamin
        ///Gabriel
        ///Henry
        ///Sebastian
        ///Daniel
        ///Alexander
        ///Julian
        ///Grayson
        ///Matthew
        ///Ethan
        ///Samuel
        ///Dylan
        ///Jayden
        ///Aiden
        ///Luke
        ///Ezekiel
        ///Lincoln
        ///Jaxon
        ///Theodore
        ///Kingston
        ///Ryker
        ///Anthony
        ///Josiah
        ///Isaiah
        ///Easton
        ///Hudson
        ///Jose
        ///Levi
        ///Sawyer
        ///Braxton
        ///Isaac
        ///Bridger
        ///Cooper
        ///Gordon  
        ///Dalton  
        ///Alphonse  
        ///Hosea  
        ///Jeramy  
        ///Johnie  
        ///Willis  
        ///Pete  
        ///Toby   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstMaleNames {
            get {
                return ResourceManager.GetString("FirstMaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.012292728
        ///0.012995767
        ///0.012765879
        ///0.012792709
        ///0.013055038
        ///0.012999548
        ///0.012930114
        ///0.012990116
        ///0.012814865
        ///0.012826938
        ///0.01270173
        ///0.012246873
        ///0.011777462
        ///0.011626521
        ///0.011485864
        ///0.011546476
        ///0.011829822
        ///0.012002553
        ///0.012234067
        ///0.012719373
        ///0.013076868
        ///0.013512131
        ///0.01412232
        ///0.014480709
        ///0.014695922
        ///0.014732306
        ///0.015040327
        ///0.015244767
        ///0.015010123
        ///0.015015651
        ///0.014899955
        ///0.015106062
        ///0.014924184
        ///0.014858165
        ///0.014756168
        ///0.014271676
        ///0.013932271
        ///0.013394199
        ///0.013016052
        ///0.01279 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialAgeDistribution {
            get {
                return ResourceManager.GetString("InitialAgeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Jones
        ///Williams
        ///Brown
        ///Wilson
        ///Taylor
        ///Johnson
        ///White
        ///Martin
        ///Anderson
        ///Thompson
        ///Nguyen
        ///Turner
        ///Walker
        ///Harris
        ///Lee
        ///Ryan
        ///Robinson
        ///Kelly
        ///King
        ///Smith
        ///Wilson
        ///Williams
        ///Brown
        ///Taylor
        ///Jones
        ///Singh
        ///Wang
        ///Anderson
        ///Li
        ///Thompson
        ///Walker
        ///Lee
        ///Chen
        ///Patel
        ///Zhang
        ///Martin
        ///King
        ///Harris
        ///Kumar.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
